# tap
tap "jesseduffield/lazygit"
tap "jesseduffield/lazydocker"
# tap "koekeishiya/formulae"

# formulae
brew "asdf"
brew "awscli"
brew "bat"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git-delta"
brew "htop"
brew "imagemagick"
brew "jesseduffield/lazygit/lazygit"
brew "jesseduffield/lazydocker/lazydocker"
brew "jq"
brew "koekeishiya/formulae/skhd"
# brew "koekeishiya/formulae/yabai"
brew "lf"
brew "libpq"
brew "ncdu"
brew "neofetch"
brew "pandoc"
brew "pgcli"
brew "ripgrep"
brew "scc"
brew "starship"
brew "telnet"
brew "tldr"
brew "tmux"
brew "tree"
brew "wxwidgets"
brew "xclip"
brew "youtube-dl"

# cask
cask "alacritty"
cask "arc"
# cask "basictex"
# cask "brave-browser"
cask "discord"
cask "docker"
cask "firefox"
# cask "flux"
cask "google-chrome"
# cask "karabiner-elements"
# cask "notion"
cask "obsidian"
cask "raycast"
# cask "session-manager-plugin"
# cask "signal"
# cask "slack"
cask "spotify"
# cask "tableplus"
cask "telegram"
# cask "ubersicht" # for simple-bar
cask "visual-studio-code"
cask "whatsapp"
