format = """
$character\
$directory\
$git_branch\
$git_status\
$cmd_duration"""

add_newline = false

[character]
success_symbol = "[Ⲗ](bold blue) "
error_symbol = "[✖](bold red) "

[directory]
truncation_length = 1

[git_branch]
symbol = ""
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "bold white"

[git_status]
style = "bold yellow"
format = '([$all_status$ahead_behind]($style) )'
untracked = "*"
stashed = ""
modified = "*"
staged = "*"
renamed = "*"
deleted = "*"

[cmd_duration]
format = "[$duration]($style) "
style = "bold white"
