[tools]
codex = "latest"
elixir = "1.19"
erlang = "28"
go = "latest"
golangci-lint = "latest"
neovim = "latest"
node = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
opencode = "latest"
pipx = "latest"
"pipx:gamdl" = "latest"
pnpm = "latest"
python = "latest"
usage = "latest"
usql = "latest"
